[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings=["MAINNET_RPC_URL=https://eth-mainnet.g.alchemy.com/v2/ZQdKORYAIJfSwtXt4pm1S5k5slGjXNki"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
